### ISSUE TITLE
Update UG to alert about Late Night appointments (0000 vs 2359) for addAppt

### ISSUE THREAD

**Issue by PresleyChew** [AY2425S1-CS2103T-F12-3/tp#222]
![image_2024-10-27_171457874](https://github.com/user-attachments/assets/cf3f4d02-9ff0-42b4-ab3d-669dc437f81e)

**Comment by yadobler** [comment]
Will not fix

Current implementation limits appointment to same day start and end times only. If required, set end time to **2359** since _0000_ is the start of the next day

Will update UG to add disclaimer
