### ISSUE TITLE
Bug: Invalid command format message in listPrio

### ISSUE THREAD

**Issue by hweinian** [AY2425S1-CS2103T-F12-3/tp#228]
![image](https://github.com/user-attachments/assets/cecc2cf5-b065-4f9c-8ab8-051b0d513696)

Currently, the invalid command format in listPrio indicate the "Parameters: !/Priority". However, there is only 1 parameter. Thus, it should be "Parameter: !/Priority"

**Comment by PresleyChew** [comment]
Good catch!
