### ISSUE TITLE
Bug: AddMedCon accepts CONDITIONS as case-insensitive , not documented in UG

### ISSUE THREAD

**Issue by yadobler** [AY2425S1-CS2103T-F12-3/tp#260]
![image](https://github.com/user-attachments/assets/571a5f3a-ac47-435f-81c6-c72a7cfe099d)

There's two things here:
1. multiple `CONDITIONS` that are the same is accepted even if subsequent duplicated are ignored (**do note this in UG if intended**)
2. `CONDITIONS` is taken as case-insensitive (**not documented in UG**)

Snippet of CONDITION parameter constaints:
![image](https://github.com/user-attachments/assets/7c2249c0-158c-483b-9a61-22b2422d2e55)

Snippet of AddMedCon usage:
![image](https://github.com/user-attachments/assets/b37a2dc0-3be0-4197-a25f-7965d3810362)

**Comment by TechRaj** [comment]
Resolved in PR #254
