### ISSUE TITLE
UG does not define "Panel" despite being referred to

### ISSUE THREAD

**Issue by yadobler** [AY2425S1-CS2103T-F12-3/tp#262]
This is the GUI overview:

![image](https://github.com/user-attachments/assets/2fa318bd-8ade-4e0f-b21a-56f61f46171e)

These are examples of *panel* being referenced (5/14 found):

![image](https://github.com/user-attachments/assets/83f549dc-e0cd-4fb6-8030-11a4a69367a6)
![image](https://github.com/user-attachments/assets/64099e6c-185c-408d-bfd1-165a66d82aec)
![image](https://github.com/user-attachments/assets/f8971a99-c145-411d-b471-44be03f918bc)
![image](https://github.com/user-attachments/assets/3c032254-1d9d-4625-9896-364752501c94)
![image](https://github.com/user-attachments/assets/8ae73f97-66bf-434e-83ab-5cbda4ef4d8b)

**Comment by yong-zhuo** [comment]
@TechRaj just need to edit the picture to specify 'appointment list panel' and 'patient list panel', as well as in the text

**Comment by yadobler** [comment]
@TechRaj you edit the pic then I'll pull your branch and then merge and submit PR
