### ISSUE TITLE
[PE-D][Tester D] In DG quick testing, the sample add command has the nric S1234567A which already exists in the preloaded data. It would be better to provide a sample input that does not fail.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-3/tp#358]
![Screenshot (128).png](https://raw.githubusercontent.com/yuvrajaryan/ped/main/files/93a59795-00d5-47b0-b5be-2f462bcd5dc5.png)

![Screenshot (129).png](https://raw.githubusercontent.com/yuvrajaryan/ped/main/files/31e44903-eb6f-4e15-8d1c-95a17ff87d2a.png)

![Screenshot (130).png](https://raw.githubusercontent.com/yuvrajaryan/ped/main/files/77d38415-503a-49a6-bb13-990e65a0df25.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: yuvrajaryan/ped#2

**Comment by hweinian** [comment]
DG should be amended to ensure sample input does not fail.
