### ISSUE TITLE
[PE-D][Tester D] Does not allow for special characters (eg: s/o or d/o) in names

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-3/tp#359]
![Screenshot (131).png](https://raw.githubusercontent.com/yuvrajaryan/ped/main/files/a538d2a3-8d6f-4176-8891-a4d82d464a9b.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: yuvrajaryan/ped#3

**Comment by hweinian** [comment]
This could possibly be shifted to planned enhancement.
