### ISSUE TITLE
[PE-D][Tester C] Confusing terminology "used as"

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-3/tp#363]
![Screenshot 2024-11-08 at 5.29.58 PM.png](https://raw.githubusercontent.com/natlv/ped/main/files/5340654e-052f-4425-bfc0-627eb131a824.png)

Replacing NAME with n/John Doe would not work as the result would be n/n/John Doe

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: natlv/ped#3

**Comment by yong-zhuo** [comment]
Minor grammar issue from old AB3 user guide, might fix
