### ISSUE TITLE
[PE-D][Tester D] The explanation of ObservableList<Person> is unclear about what “observed” means in this context

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-3/tp#368]
![image.png](https://raw.githubusercontent.com/yuvrajaryan/ped/main/files/a6696384-ae22-4afe-847b-bc8b8d027395.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: yuvrajaryan/ped#5

**Comment by yong-zhuo** [comment]
It is presumed that the person reading the DG are current/future developers who are well verse in technical terms and will understand the terms and explanation for this DG
