### ISSUE TITLE
[PE-D][Tester C] Appointment name takes in 30 characters of input

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-3/tp#380]
![Screenshot 2024-11-08 at 5.06.19 PM.png](https://raw.githubusercontent.com/natlv/ped/main/files/48d7566a-aada-4dd8-8d37-3c9d9b437f42.png)

![Screenshot 2024-11-08 at 5.09.31 PM.png](https://raw.githubusercontent.com/natlv/ped/main/files/b76b87f7-8c76-4659-8a81-c297b20378af.png)

the documentation specifies that the appointment name should be strictly less than 30 characters, but the program allows appointment names with exactly 30 characters

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: natlv/ped#9

**Comment by TechRaj** [comment]
UG can be amended to mention "no more than 30 characters".
