### ISSUE TITLE
[PE-D][Tester D] No check for phone number

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F12-3/tp#381]
![image.png](https://raw.githubusercontent.com/yuvrajaryan/ped/main/files/9cac2ab0-1667-4dc6-82d8-2e9e3de0637f.png)
There is no validation of phone number except that its an integer.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yuvrajaryan/ped#10

**Comment by TechRaj** [comment]
Bug report unclear
