### ISSUE TITLE
[PE-D][Tester B] Medical conditions character restriction

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-3/tp#382]
![image.png](https://raw.githubusercontent.com/minhao23/ped/main/files/f72669cb-fad3-4d3d-ab39-2c9458a6b4d3.png)
There are medical conditions over 30 characters, so perhaps this limiting factor should not be put in place

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: minhao23/ped#5

**Comment by TechRaj** [comment]
Most doctors use acronyms to store medical conditions, so the 30-character limit is adequate. For instance, the disease you have used as an example is known as [DCM](https://pmc.ncbi.nlm.nih.gov/articles/PMC10783125/), which is the standard acronym used throughout medical journals and papers.

The character limit helps ensure data consistency and avoids cumbersome long condition names, which are often abbreviated by medical professionals for simplicity and efficiency. If there are any exceptions, additional details can be added in other fields, allowing for both succinct record-keeping and flexibility where needed.
