### ISSUE TITLE
[PE-D][Tester E] Command summary in UG missing some commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F12-3/tp#404]
The command summary table in the UG does not have the set priority command as well as the exit command.

Perhaps the team can look into and rectify this.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: ywllowsensor/ped#18

**Comment by PresleyChew** [comment]
Both setPriority and exit is missing from the command summary, will have to update the UG to account for those

Duplicate Issue with https://github.com/AY2425S1-CS2103T-F12-3/tp/issues/361
