### ISSUE TITLE
Rework existing commands (imported from AB3) to use NRIC over Index

### ISSUE THREAD

**Issue by yadobler** [AY2425S1-CS2103T-F12-3/tp#88]
Commands like `delete` currently uses `Index` to identify the record to be deleted. This is against our policy of using `Nric` to identify the patient record to edit. This allows for less errors as index might be mistyped, while `Nric` requires 7 digits, one of 4 categories, and a final checksum character, all correctly keyed in to ensure the correct record is edited.

**Comment by yong-zhuo** [comment]
I think #81 and #55 might cover this issue
